# Generated by Django 4.2.13 on 2026-03-07 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(help_text='Name of the loan', max_length=200)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('CAR', 'Car Loan'), ('HOME', 'Home Loan'), ('EDUCATION', 'Education Loan'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='PERSONAL', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('loan_term_months', models.IntegerField(help_text='Loan term in months')),
                ('emi_amount', models.DecimalField(decimal_places=2, help_text='Monthly EMI amount', max_digits=12)),
                ('start_date', models.DateField(help_text='Loan start date')),
                ('end_date', models.DateField(help_text='Expected loan end date')),
                ('next_emi_date', models.DateField(help_text='Next EMI due date')),
                ('lender_name', models.CharField(blank=True, help_text='Bank/lender name', max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Loan account number', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULTED', 'Defaulted'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='EMI due date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_payments', to='debts.debt')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['debt', 'is_paid'], name='debts_emipa_debt_id_72fdff_idx'), models.Index(fields=['due_date'], name='debts_emipa_due_dat_94cbc9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['owner', 'status'], name='debts_debt_owner_i_a604b4_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['next_emi_date'], name='debts_debt_next_em_1c34cb_idx'),
        ),
    ]
