# Generated by Django 4.2.13 on 2026-03-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_goal_owner_i_0c3e30_idx',
            old_name='goals_goal_owner_s_status_idx',
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_goal_end_dat_7bb13c_idx',
            old_name='goals_goal_end_dat_idx',
        ),
    ]
