# Generated by Django 3.2.25 on 2026-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenselimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['owner', 'date'], name='expenses_ex_owner_i_d056f1_idx'),
        ),
    ]
