# Generated by Django 3.2.25 on 2026-02-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_auto_20260224_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('expense_added', 'Expense Added'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('goal_created', 'Goal Created'), ('limit_updated', 'Limit Updated'), ('login_success', 'Login Success'), ('daily_limit_80', '80% Daily Limit Reached'), ('goal_near_deadline', 'Goal Near Deadline'), ('daily_limit_exceeded', 'Daily Limit Exceeded'), ('monthly_limit_exceeded', 'Monthly Limit Exceeded'), ('invalid_input', 'Invalid Input'), ('future_date', 'Future Date'), ('voice_recognition_failed', 'Voice Recognition Failed'), ('insufficient_balance', 'Insufficient Balance'), ('no_expenses', 'No Expenses Found'), ('no_search_results', 'No Search Results'), ('listening_started', 'Listening Started'), ('suspicious_login', 'Suspicious Login'), ('password_changed', 'Password Changed'), ('large_transaction', 'Large Unusual Transaction')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='userprefere_user_id_da3839_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'event_hash'], name='userprefere_event_t_9eba26_idx'),
        ),
    ]
