# Generated by Django 3.2.25 on 2026-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0004_auto_20260227_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='daily_summary_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable daily spending summary notifications'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='daily_summary_time',
            field=models.TimeField(default=None, help_text='Preferred time to receive daily spending summary'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_summary_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when daily summary was last sent', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone in IANA format (e.g., Asia/Kolkata, America/New_York)", max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('expense_added', 'Expense Added'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('goal_created', 'Goal Created'), ('limit_updated', 'Limit Updated'), ('login_success', 'Login Success'), ('daily_limit_80', '80% Daily Limit Reached'), ('goal_near_deadline', 'Goal Near Deadline'), ('daily_summary', 'Daily Spending Summary'), ('daily_limit_exceeded', 'Daily Limit Exceeded'), ('monthly_limit_exceeded', 'Monthly Limit Exceeded'), ('invalid_input', 'Invalid Input'), ('future_date', 'Future Date'), ('voice_recognition_failed', 'Voice Recognition Failed'), ('insufficient_balance', 'Insufficient Balance'), ('no_expenses', 'No Expenses Found'), ('no_search_results', 'No Search Results'), ('listening_started', 'Listening Started'), ('suspicious_login', 'Suspicious Login'), ('password_changed', 'Password Changed'), ('large_transaction', 'Large Unusual Transaction')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='userprefere_user_id_a0654f_idx'),
        ),
    ]
