# Generated by Django 4.2.13 on 2026-03-07 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_source_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='source',
            name='color',
            field=models.CharField(default='#1CC88A', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class for UI', max_length=50),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userincome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userincome',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this recurring income?'),
        ),
        migrations.AddField(
            model_name='userincome',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has income been verified?'),
        ),
        migrations.AddField(
            model_name='userincome',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userincome',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHECK', 'Check'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='BANK', max_length=20),
        ),
        migrations.AddField(
            model_name='userincome',
            name='recurring_frequency',
            field=models.CharField(choices=[('NONE', 'One-time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='userincome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='userincome',
            index=models.Index(fields=['owner', 'date'], name='userincome__owner_i_df60a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userincome',
            index=models.Index(fields=['owner', 'source'], name='userincome__owner_i_42c0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='userincome',
            index=models.Index(fields=['date'], name='userincome__date_b2688b_idx'),
        ),
        migrations.AddIndex(
            model_name='userincome',
            index=models.Index(fields=['is_recurring'], name='userincome__is_recu_7818ad_idx'),
        ),
    ]
