# Generated by Django 3.2.25 on 2026-02-26 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_simulator', '0002_card_cardtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('AMEX', 'American Express'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='merchant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SIMULATED', 'Simulated'), ('CSV_IMPORT', 'CSV Import')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CREDIT_LIMIT', 'Credit Limit Crossed'), ('LARGE_TRANSACTION', 'Large Transaction'), ('RECURRING_RENEWAL', 'Subscription Renewal'), ('SPENDING_INCREASE', 'Spending Increased')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
