# Generated by Django 4.2.13 on 2026-03-06 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_simulator', '0004_add_source_category_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_simulator.banktransaction'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_card_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_simulator.cardtransaction'),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='linked_expense_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('CREDIT_LIMIT', 'Credit Limit Crossed'), ('LARGE_TRANSACTION', 'Large Transaction'), ('RECURRING_RENEWAL', 'Subscription Renewal'), ('SPENDING_INCREASE', 'Spending Increased'), ('LOW_BALANCE', 'Low Bank Balance'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_brand',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('AMEX', 'American Express'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to='bank_simulator.card'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SIMULATED', 'Simulated'), ('CSV_IMPORT', 'CSV Import'), ('AUTO_SYNC', 'Auto Sync')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_read'], name='bank_simula_user_id_91c238_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'created_at'], name='bank_simula_user_id_8e30bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['user', 'transaction_date'], name='bank_simula_user_id_b09218_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['transaction_hash'], name='bank_simula_transac_a85d2e_idx'),
        ),
    ]
