# Generated by Django 4.2.13 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_simulator', '0006_beneficiary_transferrequest_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='linked_expense_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]

